In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from functools import reduce
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from functools import reduce
pd.options.mode.chained_assignment = None  # default='warn'
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
import sys
sys.path.append("../../../Functions and Dictionaries/") # Adds higher directory to python modules path
import geodict
namestocommon = geodict.namestocommon
geotogeoid = geodict.geotogeoid
tofullcensus = geodict.tofullcensus
import sqlite3 as sq

In [51]:
conn = sq.connect('../../../Pipeline-Census-Bureau/Outputs/CensusBureau.db')
sql_query = pd.read_sql('SELECT * FROM [BFS_CountyAnnual]', conn)
data = pd.DataFrame(sql_query)
data = data.loc[(data['State'] == 'TN')|(data['NAME'] == 'GNRC')].reset_index(drop = True)

In [52]:
data.tail(2)

,NAME,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,State
94,Wilson County,673.0,718.0,834.0,744.0,733.0,668.0,887.0,772.0,834.0,802.0,877.0,939.0,1067.0,1156.0,1306.0,1480.0,1851.0,2006.0,2307.0,TN
95,GNRC,12298.0,13544.0,14132.0,13493.0,12631.0,12991.0,15461.0,14875.0,15499.0,16211.0,17313.0,18459.0,21336.0,23945.0,23597.0,28002.0,34805.0,34671.0,37788.0,None

In [53]:
data = data[['NAME', '2019', '2020', '2021', '2022']]

In [54]:
data = data.set_index(['NAME']).transpose()
cols = data.columns
data[cols] = data[cols].astype(float)

In [55]:
data.head(2)

NAME,Anderson County,Bedford County,Benton County,Bledsoe County,Blount County,Bradley County,Campbell County,Cannon County,Carroll County,Carter County,Cheatham County,Chester County,Claiborne County,Clay County,Cocke County,Coffee County,Crockett County,Cumberland County,Davidson County,Decatur County,DeKalb County,Dickson County,Dyer County,Fayette County,Fentress County,Franklin County,Gibson County,Giles County,Grainger County,Greene County,Grundy County,Hamblen County,Hamilton County,Hancock County,Hardeman County,Hardin County,Hawkins County,Haywood County,Henderson County,Henry County,Hickman County,Houston County,Humphreys County,Jackson County,Jefferson County,Johnson County,Knox County,Lake County,Lauderdale County,Lawrence County,Lewis County,Lincoln County,Loudon County,McMinn County,McNairy County,Macon County,Madison County,Marion County,Marshall County,Maury County,Meigs County,Monroe County,Montgomery County,Moore County,Morgan County,Obion County,Overton County,Perry County,Pickett County,Polk County,Putnam County,Rhea County,Roane County,Robertson County,Rutherford County,Scott County,Sequatchie County,Sevier County,Shelby County,Smith County,Stewart County,Sullivan County,Sumner County,Tipton County,Trousdale County,Unicoi County,Union County,Van Buren County,Warren County,Washington County,Wayne County,Weakley County,White County,Williamson County,Wilson County,GNRC
2019,411.0,318.0,85.0,59.0,763.0,700.0,158.0,44.0,99.0,267.0,288.0,88.0,108.0,43.0,155.0,358.0,82.0,440.0,10777.0,54.0,97.0,371.0,184.0,356.0,121.0,201.0,281.0,182.0,110.0,340.0,57.0,319.0,3338.0,22.0,119.0,100.0,248.0,87.0,140.0,149.0,126.0,40.0,111.0,65.0,293.0,66.0,3665.0,14.0,110.0,235.0,52.0,182.0,319.0,216.0,139.0,194.0,685.0,162.0,226.0,782.0,53.0,197.0,1706.0,41.0,65.0,162.0,136.0,51.0,31.0,91.0,517.0,147.0,221.0,541.0,3028.0,89.0,73.0,894.0,11134.0,121.0,82.0,823.0,1600.0,375.0,62.0,70.0,118.0,25.0,198.0,871.0,77.0,134.0,145.0,3685.0,1306.0,23597.0
2020,441.0,337.0,76.0,69.0,869.0,747.0,177.0,98.0,169.0,287.0,360.0,116.0,145.0,47.0,164.0,337.0,83.0,408.0,12815.0,63.0,131.0,391.0,236.0,502.0,113.0,266.0,349.0,193.0,103.0,369.0,59.0,328.0,3971.0,20.0,249.0,172.0,228.0,135.0,140.0,194.0,157.0,37.0,111.0,63.0,296.0,96.0,4351.0,21.0,167.0,229.0,77.0,214.0,345.0,247.0,141.0,138.0,968.0,170.0,211.0,958.0,56.0,227.0,2436.0,15.0,104.0,174.0,105.0,43.0,21.0,92.0,497.0,137.0,253.0,528.0,4033.0,121.0,91.0,942.0,19959.0,134.0,74.0,907.0,1878.0,451.0,66.0,80.0,109.0,28.0,201.0,899.0,66.0,166.0,153.0,3793.0,1480.0,28002.0

In [56]:
data = data[['Cheatham County', 'Davidson County', 'Dickson County', 'Houston County', 'Humphreys County', 
           'Montgomery County', 'Robertson County', 'Rutherford County', 
          'Stewart County', 'Sumner County', 'Trousdale County', 'Williamson County', 'Wilson County', 'GNRC']]

In [57]:
data.head(2)

NAME,Cheatham County,Davidson County,Dickson County,Houston County,Humphreys County,Montgomery County,Robertson County,Rutherford County,Stewart County,Sumner County,Trousdale County,Williamson County,Wilson County,GNRC
2019,288.0,10777.0,371.0,40.0,111.0,1706.0,541.0,3028.0,82.0,1600.0,62.0,3685.0,1306.0,23597.0
2020,360.0,12815.0,391.0,37.0,111.0,2436.0,528.0,4033.0,74.0,1878.0,66.0,3793.0,1480.0,28002.0

In [58]:
data = data.transpose().reset_index(drop = False)

In [59]:
data.tail()

                 NAME     2019     2020     2021     2022
9       Sumner County   1600.0   1878.0   2354.0   2445.0
10   Trousdale County     62.0     66.0     59.0     83.0
11  Williamson County   3685.0   3793.0   4567.0   4700.0
12      Wilson County   1306.0   1480.0   1851.0   2006.0
13               GNRC  23597.0  28002.0  34805.0  34671.0

In [61]:
data.to_csv('../data/bfs.csv')